# Cross compiling for Raspberry pi 4/5

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update",
    "apt-get install --assume-yes libasound2-dev:arm64 libopus-dev:arm64 pkg-config cmake"
]
