[package]
name = "receiver"
version = "0.1.0"
edition = "2024"

[dependencies]
airspyhf = { path = "../airspyhf" }
pool = { path = "../pool" }
spectrum = { path = "../spectrum" }
doublemap = { path = "../doublemap" }
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
num-complex = "0.4.6"
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
bytemuck = "1.23.1"
zerocopy = { version = "0.8.25", features = ["std"] }
