[package]
name = "sidebridge"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
arrayvec = { version = "0.7.6", features = ["serde"] }
async-trait = "0.1.89"
bytes = "1.11.1"
clap = { version = "4.5.56", features = ["derive"] }
futures = "0.3.31"
nom = "8.0.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["full"] }
tokio-serial = "5.4.5"
tokio-stream = { version = "0.1.18", features = ["sync"] }
tokio-util = { version = "0.7.18", features = ["codec"] }
url = "2"

[[bin]]
name = "serial-bridge"
path = "src/bin/serial_bridge.rs"

[[bin]]
name = "civ-client"
path = "src/bin/civ_client.rs"

[[bin]]
name = "civ-poll"
path = "src/bin/civ_poll.rs"
