[package]
name = "serial-bridge"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bytes = "1.11.1"
clap = { version = "4.5.56", features = ["derive"] }
futures = "0.3.31"
nom = "8.0.0"
tokio = { version = "1.49.0", features = ["full"] }
tokio-serial = "5.4.5"
tokio-util = { version = "0.7.18", features = ["codec"] }
tokio-utils = "0.1.2"
